### ISSUE TITLE
영어로 Issue / Commit 달기 제안

### ISSUE THREAD

**Issue by souljungkim** [suy427/mamas-estate#22]
(해당이슈에 대해 적당한 이슈템플릿을 몰라, 부득이 다음과 같이 작성하였으니, 부당할 경우 지적부탁합니다.)

`Issue` 와 `Commit Message` 를 `영어로` 달면 어떨까요?

### 왜 영어인가?
이것이 @suy427이 원하는 영어학습에 대한 좋은 촉진제가 될 수 있을 것이라 확신합니다.

영어 사대주의자는 아니지만, `개발활동에 필수불가결의 요소`임에는 틀림없습니다.

처음부터 깔끔하지 않을 것이라고 생각되지만 분명 `나중에는 훌륭한 스펙`이 되어 있지 않을까 생각합니다.

두려울 필요없습니다.

[Google Translator](https://translate.google.co.kr/)가 우리를 도와줄 겁니다.

하지만, 모든 것을 고려해야하는 Project 마스터(@suy427)의 선택에 달렸습니다.

또한 아래 좋은 자료가 있기에 참조했습니다.

### Reference
- 좋은 git commit 메시지를 위한 영어 사전:  https://blog.ull.im/engineering/2019/03/10/logs-on-git.html
- 좋은 git 커밋 메시지를 작성하기 위한 7가지 약속: https://meetup.toast.com/posts/106

**Comment by suy427** [comment]
thx for your advice :D
i usually do prefer to use english 
but i became too loose while working alone.
i willing to accept you and thank you for attention
