### ISSUE TITLE
Install code coverage tool

### ISSUE THREAD

**Issue by souljungkim** [suy427/mamas-estate#23]
## 현상황
Coverage 분석툴의 부재

## 문제점
추후 테스트에 대한 분석이 어려울 것으로 예상됨.

### 1. Code Coverage 도입
Test Code에 의해  Source Code의 모든 부분을 1번 이상은 지나갈 것을 권장합니다.

Coverage의 상승이 제품의 품질의 상승과 직결된다고는 할 수 없지만, 
추후 `Test code를 면밀히 작성할 수 있는 척도`가 되며 `사소할 실수`와 `반복되는 Runtime오류를 미연에 방지`할 수 있는 가장 심플한 방법이라고 생각합니다.

### 2. Java
- Junit 
  - Java code 테스트를 위한 라이브러리
- Jacoco
  - HTML view페이지로 Coverage report 제작
  - `Gradle task`로 작성하여 빌드시 `build/report/jacoco`에 Code Coverage HTML report가 생성됨
  - 추후 `SonarQube`와 연동가능
- Coveralls
  - Gradle task로 작성하여, CI와 연계하고 CI script에서 해당 task를 호출하여 Jacoco로 만든 report를 coveralls.io로 전송하고 간편하게 확인할 수 있음.
  - Github project repository와 연계하여 Webpage([coveralls.io](https://coveralls.io/))에서 쉽게 확인 가능.
  - 통상 Github `README.md`에 `Badge`를 달아 `project를 신뢰`할 수 있는 `객관적인 수치`를 percentage로 표시 가능

### 3. Javascript (or NodeJS)
- Mocha
  - 기본적인 테스팅 도구
- NYC
  - `coverage` 폴더에 Code Coverage HTML report가 생성됨
- Coveralls
  - nyc로 만든 report를 coveralls.io로 전송하고 간편하게 확인할 수 있음.
  - Github project repository와 연계하여 Webpage([coveralls.io](https://coveralls.io/))에서 쉽게 확인 가능.
  - 통상 Github `README.md`에 `Badge`를 달아 `project를 신뢰`할 수 있는 `객관적인 수치`를

**Comment by suy427** [comment]
i think i have to set the priorities of these issues.
needless to say, the code coverage and testing environment is super important.
i feel that of course but i have to do lots of things and i have no guarantee to complete these things all.

**Comment by souljungkim** [comment]
@suy427 It is very simple. 
I have already applied it to other projects. 
After applying the CI(#24), I will refer to the changes here (https://github.com/avaj-java/installer-maker/pull/80/files) and apply it to this project.
It will be helpful for this project.

**Comment by souljungkim** [comment]
@suy427 I think you have already done a great job. `You can close this issue.`

**Comment by suy427** [comment]
thx :)
